services:
  XXXX: # Project name
    build:
      context: .
      dockerfile: Dockerfile
    image: XXXX-XXXX:XXXX   # 명시적으로 이미지 이름 지정
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # 로컬 소스코드 디렉토리 마운트 (경로는 상황에 맞게 수정)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
